// frontend/src/components/GitLog/graph/components/IndexPseudoRow.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useGitContext } from '../../composables/useGitContext'
import { useGraphContext } from '../../composables/useGraphContext'
import type { GraphColumnState } from '../GraphMatrixBuilder/types'
import GraphRow from './GraphRow.vue'

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const { indexCommit } = useGitContext()
const { graphWidth, isHeadCommitVisible } = useGraphContext()

// ---------------------------------------------------------------------------
// Computed values
// ---------------------------------------------------------------------------

/**
 * Builds the column states for the index pseudo-row.
 *
 * The first column (index 0) contains the node and vertical line.
 * A bottom breakpoint is shown when the HEAD commit is not visible
 * in the current pagination, to indicate a gap.
 */
const indexColumns = computed<GraphColumnState[]>(() => {
  const columns = new Array<GraphColumnState>(graphWidth.value).fill({})

  columns[0] = {
    isNode: true,
    isVerticalLine: true,
    isBottomBreakPoint: !isHeadCommitVisible.value,
  }

  return columns
})
</script>

<template>
  <GraphRow
    v-if="indexCommit"
    :id="0"
    :commit="indexCommit"
    :columns="indexColumns"
  />
</template>

// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Graph/strategies/Grid/components/IndexPseudoRow/IndexPseudoRow.tsx
import { GraphRow } from 'modules/Graph/strategies/Grid/components/GraphRow'
import { GraphColumnState } from 'modules/Graph/strategies/Grid/components/GraphColumn'
import { useMemo } from 'react'
import { useGitContext } from 'context/GitContext'
import { useGraphContext } from 'modules/Graph/context'

export const IndexPseudoRow = () => {
  const { indexCommit } = useGitContext()
  const { graphWidth, isHeadCommitVisible } = useGraphContext()

  const indexColumns = useMemo(() => {
    const columns = new Array<GraphColumnState>(graphWidth).fill({})

    columns[0] = {
      isNode: true,
      isVerticalLine: true,
      isBottomBreakPoint: !isHeadCommitVisible
    }

    return columns
  }, [graphWidth, isHeadCommitVisible])

  if (indexCommit) {
    return (
      <GraphRow
        id={0}
        key={'index'}
        commit={indexCommit}
        columns={indexColumns}
      />
    )
  }

  return null
}
