// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Graph/strategies/Grid/components/BreakPoint/BreakPoint.tsx
import { BreakPointProps } from './types'
import classNames from 'classnames'
import classes from './BreakPoint.module.scss'
import { useGraphContext } from 'modules/Graph/context'
import { CSSProperties, useMemo } from 'react'

export const BreakPoint = ({ position, className, color, style }: BreakPointProps) => {
  const { breakPointTheme } = useGraphContext()

  const commonStyles = useMemo<CSSProperties>(() => ({
    '--breakpoint-colour': color
  } as CSSProperties), [color])

  switch (breakPointTheme) {
    case 'slash': {
      return (
        <div
          style={{ ...commonStyles, ...style?.slash }}
          data-testid={`graph-break-point-slash-${position}`}
          className={classNames(
            classes.Slash,
            classes[`Slash--${position}`],
            className
          )}
        />
      )
    }
    case 'dot': {
      return (
        <div
          style={{ ...commonStyles, ...style?.dot }}
          data-testid={`graph-break-point-dot-${position}`}
          className={classNames(
            classes.Dot,
            classes[`Dot--${position}`],
            className
          )}
        />
      )
    }
    case 'ring': {
      return (
        <div
          style={{ ...commonStyles, ...style?.ring }}
          data-testid={`graph-break-point-ring-${position}`}
          className={classNames(
            classes.Ring,
            classes[`Ring--${position}`],
            className
          )}
        />
      )
    }
    case 'zig-zag': {
      return (
        <div
          style={{ ...commonStyles, ...style?.['zig-zag'] }}
          data-testid={`graph-break-point-zig-zag-${position}`}
          className={classNames(
            classes.ZigZag,
            classes[`ZigZag--${position}`],
            className
          )}
        />
      )
    }
    case 'line': {
      return (
        <div
          style={{ ...commonStyles, ...style?.['line'] }}
          data-testid={`graph-break-point-line-${position}`}
          className={classNames(
            classes.Line,
            classes[`Line--${position}`],
            className
          )}
        />
      )
    }
    case 'double-line': {
      return (
        <div
          style={{ ...commonStyles, ...style?.['double-line'] }}
          data-testid={`graph-break-point-double-line-${position}`}
          className={classNames(
            classes.DoubleLine,
            classes[`DoubleLine--${position}`],
            className
          )}
        />
      )
    }
    case 'arrow': {
      return (
        <div
          style={{ ...commonStyles, ...style?.arrow }}
          data-testid={`graph-break-point-arrow-${position}`}
          className={classNames(
            classes.Arrow,
            classes[`Arrow--${position}`],
            className
          )}
        />
      )
    }
  }
}

// frontend/src/components/GitLog/graph/components/BreakPoint.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'
import { useGraphContext } from '../../composables/useGraphContext'
import type { BreakPointTheme } from '../../types'
import styles from './BreakPoint.module.scss'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  position: 'top' | 'bottom'
  colour: string
  styleOverrides?: Partial<Record<BreakPointTheme, CSSProperties>>
}>()

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const { breakPointTheme } = useGraphContext()

// ---------------------------------------------------------------------------
// Computed values
// ---------------------------------------------------------------------------

const commonStyles = computed<CSSProperties>(() => ({
  '--breakpoint-colour': props.colour,
} as CSSProperties))

/**
 * Maps the breakpoint theme to the corresponding SCSS module class name
 * and position modifier.
 */
const themeClassMap: Record<BreakPointTheme, string> = {
  'slash': 'Slash',
  'dot': 'Dot',
  'ring': 'Ring',
  'zig-zag': 'ZigZag',
  'line': 'Line',
  'double-line': 'DoubleLine',
  'arrow': 'Arrow',
}

const themeClass = computed(() => {
  const className = themeClassMap[breakPointTheme.value]
  return className
})

const elementClasses = computed(() => [
  styles[themeClass.value],
  styles[`${themeClass.value}--${props.position}`],
])

const elementStyle = computed<CSSProperties>(() => ({
  ...commonStyles.value,
  ...(props.styleOverrides?.[breakPointTheme.value] ?? {}),
}))

const testId = computed(() =>
  `graph-break-point-${breakPointTheme.value}-${props.position}`,
)
</script>

<template>
  <div
    :data-testid="testId"
    :class="elementClasses"
    :style="elementStyle"
  />
</template>
