// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Graph/strategies/Grid/components/CurvedEdge/CurvedEdge.tsx
import styles from './CurvedEdge.module.scss'
import { CurvedEdgeProps } from './types'
import { CURVE_SIZE } from 'constants/constants'

export const CurvedEdge = ({ id, colour, path, dashed }: CurvedEdgeProps) => {
  return (
    <svg
      id={id}
      data-testid={id}
      width={CURVE_SIZE}
      height={CURVE_SIZE}
      viewBox={'0 0 100 100'}
      className={styles.curve}
      preserveAspectRatio='none'
    >
      <path
        d={path}
        stroke={colour}
        strokeWidth="2"
        fill="transparent"
        vectorEffect='non-scaling-stroke'
        strokeDasharray={dashed ? '2 2': undefined}
      />
    </svg>
  )
}

// frontend/src/components/GitLog/graph/components/CurvedEdge.vue
<script setup lang="ts">
import { CURVE_SIZE } from '../../constants'
import styles from './CurvedEdge.module.scss'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

defineProps<{
  id: string
  colour: string
  path: string
  dashed?: boolean
}>()
</script>

<template>
  <svg
    :id="id"
    :data-testid="id"
    :width="CURVE_SIZE"
    :height="CURVE_SIZE"
    viewBox="0 0 100 100"
    :class="styles.curve"
    preserveAspectRatio="none"
  >
    <path
      :d="path"
      :stroke="colour"
      stroke-width="2"
      fill="transparent"
      vector-effect="non-scaling-stroke"
      :stroke-dasharray="dashed ? '2 2' : undefined"
    />
  </svg>
</template>
