// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Graph/strategies/Grid/components/GraphRow/GraphRow.tsx
import { GraphRowProps } from './types'
import { GraphColumn } from 'modules/Graph/strategies/Grid/components/GraphColumn'
import { getEmptyColumnState } from 'modules/Graph/strategies/Grid/utility/getEmptyColumnState'
import { useGraphContext } from 'modules/Graph/context'

export const GraphRow = ({ id, commit, columns }: GraphRowProps) => {
  const { graphWidth, orientation } = useGraphContext()

  return (
    <>
      {new Array(graphWidth).fill(0).map((_, index) => {
        const normalisedIndex = orientation === 'normal'
        ? index
        : graphWidth - 1 - index

        return (
          <GraphColumn
            rowIndex={id}
            commit={commit}
            index={normalisedIndex}
            commitNodeIndex={columns.findIndex(col => col.isNode)}
            key={`row_${commit ? commit.hash : 'index'}_column_${normalisedIndex}}`}
            // If there is no state for the given index, then we're in a virtual column, so use an empty state
            state={columns[normalisedIndex] ?? getEmptyColumnState({ columns: graphWidth })}
          />
        )
      })}
    </>
  )
}

// frontend/src/components/GitLog/graph/components/GraphRow.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useGraphContext } from '../../composables/useGraphContext'
import type { Commit } from '../../types'
import type { GraphColumnState } from '../GraphMatrixBuilder/types'
import GraphColumn from './GraphColumn.vue'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  /** The zero-based row id used for tabIndex and indexing. */
  id: number

  /** The commit represented by this row. */
  commit: Commit

  /** The column states for this row. */
  columns: GraphColumnState[]
}>()

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const { graphWidth, orientation } = useGraphContext()

// ---------------------------------------------------------------------------
// Computed values
// ---------------------------------------------------------------------------

const commitNodeIndex = computed(() =>
  props.columns.findIndex(col => col.isNode),
)

/**
 * The empty state used for virtual columns that have no entry in
 * the column states array.
 */
const emptyColumnState: GraphColumnState = {}
</script>

<template>
  <GraphColumn
    v-for="i in graphWidth"
    :key="`row_${commit.hash}_column_${orientation === 'normal' ? i - 1 : graphWidth - i}`"
    :row-index="id"
    :commit="commit"
    :index="orientation === 'normal' ? i - 1 : graphWidth - i"
    :commit-node-index="commitNodeIndex"
    :state="columns[orientation === 'normal' ? i - 1 : graphWidth - i] ?? emptyColumnState"
  />
</template>
