// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Graph/strategies/Grid/components/HeadCommitVerticalLine/HeadCommitVerticalLine.tsx
import classNames from 'classnames'
import styles from './HeadCommitVerticalLine.module.scss'
import { HeadCommitVerticalLineProps } from './types'

export const HeadCommitVerticalLine = ({ columnColour }: HeadCommitVerticalLineProps) => {
  return (
    <div
      id='head-commit-vertical-line'
      data-testid='head-commit-vertical-line'
      style={{
        height: '50%',
        top: '50%',
        borderRight: `2px solid ${columnColour}`
      }}
      className={classNames(styles.line, styles.vertical)}
    />
  )
}

// frontend/src/components/GitLog/graph/components/HeadCommitVerticalLine.vue
<script setup lang="ts">
import styles from './HeadCommitVerticalLine.module.scss'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

defineProps<{
  columnColour: string
}>()
</script>

<template>
  <div
    id="head-commit-vertical-line"
    data-testid="head-commit-vertical-line"
    :style="{
      height: '50%',
      top: '50%',
      borderRight: `2px solid ${columnColour}`,
    }"
    :class="[styles.line, styles.vertical]"
  />
</template>
