// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Graph/strategies/Grid/components/IndexPseudoCommitNode/IndexPseudoCommitNode.tsx
import classNames from 'classnames'
import styles from './IndexPseudoCommitNode.module.scss'
import { useTheme } from 'hooks/useTheme'
import { IndexPseudoCommitNodeProps } from 'modules/Graph/strategies/Grid/components/IndexPseudoCommitNode/types'
import { useGraphContext } from 'modules/Graph/context'

export const IndexPseudoCommitNode = ({ animate, columnColour }: IndexPseudoCommitNodeProps) => {
  const { nodeSize } = useGraphContext()
  const { shiftAlphaChannel } = useTheme()

  return (
    <div
      id='index-pseudo-commit-node'
      data-testid='index-pseudo-commit-node'
      className={classNames(
        styles.indexNode,
        { [styles.spin]: animate },
      )}
      style={{
        width: nodeSize,
        height: nodeSize,
        border: `2px dotted ${shiftAlphaChannel(columnColour, 0.5)}`,
        backgroundColor: shiftAlphaChannel(columnColour, 0.05),
      }}
    />
  )
}

// frontend/src/components/GitLog/graph/components/IndexPseudoCommitNode.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'
import { useTheme } from '../../composables/useTheme'
import { useGraphContext } from '../../composables/useGraphContext'
import styles from './IndexPseudoCommitNode.module.scss'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  columnColour: string
  animate: boolean
}>()

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const { nodeSize } = useGraphContext()
const { shiftAlphaChannel } = useTheme()

// ---------------------------------------------------------------------------
// Computed values
// ---------------------------------------------------------------------------

const nodeStyles = computed<CSSProperties>(() => ({
  width: `${nodeSize.value}px`,
  height: `${nodeSize.value}px`,
  border: `2px dotted ${shiftAlphaChannel(props.columnColour, 0.5)}`,
  backgroundColor: shiftAlphaChannel(props.columnColour, 0.05),
}))
</script>

<template>
  <div
    id="index-pseudo-commit-node"
    data-testid="index-pseudo-commit-node"
    :class="[
      styles.indexNode,
      animate && styles.spin,
    ]"
    :style="nodeStyles"
  />
</template>
