// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Graph/strategies/Grid/components/SkeletonGraph/SkeletonGraph.tsx
import { GraphRow } from 'modules/Graph/strategies/Grid/components/GraphRow'
import { usePlaceholderData } from 'modules/Graph/strategies/Grid/hooks/usePlaceholderData'

export const SkeletonGraph = () => {
  const { placeholderData } = usePlaceholderData()
  
  return (
    <>
      {placeholderData.map(({ commit, columns }, i) => (
        <GraphRow
          id={i}
          commit={commit}
          columns={columns}
          key={`skeleton-row_${commit.hash}`}
        />
      ))}
    </>
  )
}

// frontend/src/components/GitLog/graph/components/SkeletonGraph.vue
<script setup lang="ts">
import { usePlaceholderData } from '../../composables/usePlaceholderData'
import GraphRow from './GraphRow.vue'

// ---------------------------------------------------------------------------
// Data
// ---------------------------------------------------------------------------

const { placeholderData } = usePlaceholderData()
</script>

<template>
  <GraphRow
    v-for="({ commit, columns }, rowIndex) in placeholderData"
    :key="`skeleton-row_${commit.hash}`"
    :commit="commit"
    :columns="columns"
  />
</template>
