// frontend/src/components/GitLog/table/components/TableRow.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue'
import { computed } from 'vue'
import { ROW_HEIGHT, BACKGROUND_HEIGHT_OFFSET, DEFAULT_NODE_SIZE } from '../../constants'
import { useGitContext } from '../../composables/useGitContext'
import { useTheme } from '../../composables/useTheme'
import { useSelectCommit } from '../../composables/useSelectCommit'
import type { Commit, CustomTableRowProps } from '../../types'
import CommitMessageData from './CommitMessageData.vue'
import AuthorData from './AuthorData.vue'
import TimestampData from './TimestampData.vue'
import styles from './TableRow.module.scss'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = withDefaults(defineProps<{
  index: number
  commit: Commit
  isPlaceholder?: boolean
  rowStyleOverrides?: CSSProperties
  dataStyleOverrides?: CSSProperties
}>(), {
  isPlaceholder: false,
})

// ---------------------------------------------------------------------------
// Slots
// ---------------------------------------------------------------------------

defineSlots<{
  row?(props: CustomTableRowProps): unknown
}>()

// ---------------------------------------------------------------------------
// Contexts and composables
// ---------------------------------------------------------------------------

const {
  textColour,
  hoverColour,
  reduceOpacity,
  getCommitColour,
  shiftAlphaChannel,
} = useTheme()

const { selectCommitHandler } = useSelectCommit()

const {
  selectedCommit,
  previewedCommit,
  enableSelectedCommitStyling,
  enablePreviewedCommitStyling,
} = useGitContext()

// ---------------------------------------------------------------------------
// Row state
// ---------------------------------------------------------------------------

const isRowSelected = computed(() => selectedCommit.value?.hash === props.commit.hash)
const isRowPreviewed = computed(() => previewedCommit.value?.hash === props.commit.hash)

// ---------------------------------------------------------------------------
// Background colour
// ---------------------------------------------------------------------------

const backgroundColour = computed(() => {
  if (isRowSelected.value && enableSelectedCommitStyling.value) {
    if (props.isPlaceholder) {
      return hoverColour.value
    }

    const colour = getCommitColour(props.commit)
    return reduceOpacity(colour, 0.15)
  }

  if (isRowPreviewed.value && enablePreviewedCommitStyling.value) {
    return hoverColour.value
  }

  return 'transparent'
})

// ---------------------------------------------------------------------------
// Background gradient style
// ---------------------------------------------------------------------------

const backgroundStyles = computed(() => {
  const height = DEFAULT_NODE_SIZE + BACKGROUND_HEIGHT_OFFSET
  const padding = (ROW_HEIGHT - height) / 2
  const end = padding + height

  return {
    background: `linear-gradient(
      to bottom,
      transparent ${padding}px,
      ${backgroundColour.value} ${padding}px,
      ${backgroundColour.value} ${end}px,
      transparent ${end}px
    )`,
  }
})

// ---------------------------------------------------------------------------
// Cell styling
// ---------------------------------------------------------------------------

const isMergeCommit = computed(() => props.commit.parents.length > 1)

const shouldReduceOpacity = computed(
  () => !props.isPlaceholder && (isMergeCommit.value || props.commit.hash === 'index'),
)

const shouldRenderHyphenValue = computed(
  () => props.commit.hash === 'index' || props.isPlaceholder,
)

const tableDataStyle = computed<CSSProperties>(() => ({
  lineHeight: `${ROW_HEIGHT}px`,
  color: shiftAlphaChannel(textColour.value, shouldReduceOpacity.value ? 0.4 : 1),
  ...backgroundStyles.value,
  ...props.dataStyleOverrides,
}))

// ---------------------------------------------------------------------------
// Event handlers
// ---------------------------------------------------------------------------

function handleClick() {
  selectCommitHandler.onClick(props.commit)
}

function handleMouseOver() {
  selectCommitHandler.onMouseOver(props.commit)
}

function handleMouseOut() {
  selectCommitHandler.onMouseOut()
}
</script>

<template>
  <!-- Custom row via scoped slot -->
  <div
    v-if="$slots.row"
    :id="`vue-git-log-table-row-${index}`"
    :data-testid="`vue-git-log-table-row-${index}`"
    @click="handleClick"
    @mouseover="handleMouseOver"
    @mouseout="handleMouseOut"
  >
    <slot
      name="row"
      :commit="commit"
      :selected="isRowSelected"
      :previewed="isRowPreviewed"
      :background-colour="backgroundColour"
    />
  </div>

  <!-- Default row layout -->
  <div
    v-else
    :id="`vue-git-log-table-row-${index}`"
    :data-testid="`vue-git-log-table-row-${index}`"
    :class="styles.row"
    :style="rowStyleOverrides"
    @click="handleClick"
    @mouseover="handleMouseOver"
    @mouseout="handleMouseOut"
  >
    <CommitMessageData
      :index="index"
      :style="tableDataStyle"
      :commit-message="commit.message"
      :is-index="commit.hash === 'index'"
    />

    <AuthorData
      :index="index"
      :author="commit.author"
      :style="tableDataStyle"
      :is-placeholder="shouldRenderHyphenValue"
    />

    <TimestampData
      :index="index"
      :style="tableDataStyle"
      :timestamp="commit.committerDate"
      :is-placeholder="shouldRenderHyphenValue"
    />
  </div>
</template>

// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Table/components/TableRow/TableRow.tsx
import styles from './TableRow.module.scss'
import { GitLogTableRowProps } from './types'
import { cloneElement, CSSProperties, useMemo } from 'react'
import { useTheme } from 'hooks/useTheme'
import { useGitContext } from 'context/GitContext'
import { useSelectCommit } from 'hooks/useSelectCommit'
import { BACKGROUND_HEIGHT_OFFSET, ROW_HEIGHT } from 'constants/constants'
import { CommitMessageData } from 'modules/Table/components/CommitMessageData'
import { AuthorData } from 'modules/Table/components/AuthorData'
import { TimestampData } from 'modules/Table/components/TimestampData'

export const TableRow = ({
  row,
  index,
  commit,
  isPlaceholder,
  rowStyleOverrides,
  dataStyleOverrides,
  ...props
}: GitLogTableRowProps) => {
  const {
    textColour,
    hoverColour,
    reduceOpacity,
    getCommitColour,
    shiftAlphaChannel
  } = useTheme()

  const { selectCommitHandler } = useSelectCommit()
  const { selectedCommit, previewedCommit, nodeSize, enableSelectedCommitStyling, enablePreviewedCommitStyling } = useGitContext()

  const isRowSelected = selectedCommit?.hash === commit.hash
  const isRowPreviewed = previewedCommit?.hash === commit.hash
  const isMergeCommit = commit.parents.length > 1

  const backgroundColour = useMemo(() => {
    if (isRowSelected && enableSelectedCommitStyling) {
      if (isPlaceholder) {
        return hoverColour
      }

      const colour = getCommitColour(commit)
      return reduceOpacity(colour, 0.15)
    }

    if (isRowPreviewed && enablePreviewedCommitStyling) {
      return hoverColour
    }

    return 'transparent'
  }, [getCommitColour, commit, isRowSelected, enableSelectedCommitStyling, isRowPreviewed, enablePreviewedCommitStyling, isPlaceholder, reduceOpacity, hoverColour])

  const backgroundStyles = useMemo(() => {
    const height = nodeSize + BACKGROUND_HEIGHT_OFFSET
    const padding = (ROW_HEIGHT - height) / 2
    const end = padding + height

    return {
      background: `linear-gradient(
        to bottom, 
        transparent ${padding}px, 
        ${backgroundColour} ${padding}px,
        ${backgroundColour} ${end}px,
        transparent ${end}px
      )`
    }
  }, [backgroundColour, nodeSize])

  const shouldRenderHyphenValue = commit.hash === 'index' || Boolean(isPlaceholder)
  const shouldReduceOpacity = !isPlaceholder && (isMergeCommit || commit.hash === 'index')

  const tableDataStyle: CSSProperties = {
    lineHeight: `${ROW_HEIGHT}px`,
    color: shiftAlphaChannel(textColour, shouldReduceOpacity ? 0.4 : 1),
    ...backgroundStyles,
    ...dataStyleOverrides
  }
  
  const rowContainerProps = {
    id: `react-git-log-table-row-${index}`,
    onMouseOut: selectCommitHandler.onMouseOut,
    'data-testid': `react-git-log-table-row-${index}`,
    onClick: () => selectCommitHandler.onClick(commit),
    onMouseOver: () => selectCommitHandler.onMouseOver(commit)
  }

  if (row) {
    const customRowElement = row({
      commit,
      selected: isRowSelected,
      previewed: isRowPreviewed,
      backgroundColour
    })

    return cloneElement(customRowElement, {
      ...rowContainerProps,
      ...customRowElement.props
    })
  }

  return (
    <div
      {...rowContainerProps}
      style={rowStyleOverrides}
      className={styles.row}
      {...props}
    >
      <CommitMessageData
        index={index}
        style={tableDataStyle}
        commitMessage={commit.message}
        isIndex={commit.hash === 'index'}
      />

      <AuthorData
        index={index}
        author={commit.author}
        style={tableDataStyle}
        isPlaceholder={shouldRenderHyphenValue}
      />

      <TimestampData
        index={index}
        style={tableDataStyle}
        timestamp={commit.committerDate}
        isPlaceholder={shouldRenderHyphenValue}
      />
    </div>
  )
}
