// frontend/src/components/GitLog/Layout.vue
<script setup lang="ts">
import { useGitContext } from './composables/useGitContext'
import { useTheme } from './composables/useTheme'
import styles from './Layout.module.scss'

const { classes, showHeaders } = useGitContext()
const { textColour } = useTheme()
</script>

<template>
  <div
    id="vue-git-log"
    :style="classes?.containerStyles"
    :class="[styles.container, classes?.containerClass]"
  >
    <div v-if="$slots.tags" :class="styles.tags">
      <h4
        v-if="showHeaders"
        :style="{ color: textColour, marginLeft: '10px' }"
        :class="styles.title"
      >
        Branch / Tag
      </h4>

      <slot name="tags" />
    </div>

    <div v-if="$slots.graph" :class="styles.graph">
      <h4
        v-if="showHeaders"
        :style="{ color: textColour }"
        :class="styles.title"
      >
        Graph
      </h4>

      <slot name="graph" />
    </div>

    <div v-if="$slots.table" :class="styles.table">
      <slot name="table" />
    </div>
  </div>
</template>

// docs/specs/2026-02-09-git-log/react-git-log-source/components/Layout/Layout.tsx
import classNames from 'classnames'
import styles from './Layout.module.scss'
import { useGitContext } from 'context/GitContext'
import { useTheme } from 'hooks/useTheme'
import { LayoutProps } from './types'

export const Layout = ({ tags, graph, table }: LayoutProps) => {
  const { classes, showHeaders } = useGitContext()

  const { textColour } = useTheme()

  return (
    <div
      id='react-git-log'
      data-testid='react-git-log'
      style={classes?.containerStyles}
      className={classNames(styles.container, classes?.containerClass)}
    >
      {tags && (
        <div className={styles.tags}>
          {showHeaders && (
            <h4 style={{ color: textColour, marginLeft: 10 }} className={styles.title}>
              Branch / Tag
            </h4>
          )}

          {tags}
        </div>
      )}

      {graph && (
        <div className={styles.graph}>
          {showHeaders && (
            <h4 style={{ color: textColour }} className={styles.title}>
              Graph
            </h4>
          )}

          {graph}
        </div>
      )}

      {table && (
        <div className={styles.table}>
          {table}
        </div>
      )}
    </div>
  )
}
