// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Graph/core/GraphCore.tsx
import { PropsWithChildren, useEffect, useMemo } from 'react'
import styles from './GraphCore.module.scss'
import { useGitContext } from 'context/GitContext'
import { useColumnData } from 'modules/Graph/strategies/Grid/hooks/useColumnData'
import { useResize } from 'hooks/useResize'
import { DEFAULT_NODE_SIZE } from 'constants/constants'
import { GraphContext, GraphContextBag } from '../context'
import { GraphCoreProps } from 'modules/Graph/core/types'
import { CustomCommitNode } from 'modules/Graph'

export const GraphCore = <T,>({
  node,
  children,
  nodeSize = DEFAULT_NODE_SIZE,
  nodeTheme = 'default',
  breakPointTheme = 'dot',
  orientation = 'normal',
  enableResize = false,
  showCommitNodeHashes = false,
  showCommitNodeTooltips = false,
  highlightedBackgroundHeight,
  tooltip
}: PropsWithChildren<GraphCoreProps<T>>) => {
  const {
    paging,
    filter,
    setNodeSize,
    headCommit,
    setGraphOrientation,
    graphData: { graphWidth, commits }
  } = useGitContext()

  useEffect(() => {
    // Informs the wrapping GitContext about the
    // change in certain props so other components can respond.
    setNodeSize(nodeSize)
    setGraphOrientation(orientation)
  }, [nodeSize, orientation, setGraphOrientation, setNodeSize])

  const { width, ref, startResizing } = useResize()

  const visibleCommits = useMemo(() => {
    const filteredCommits = filter?.(commits) ?? commits

    if (paging) {
      return filteredCommits.slice(paging.startIndex, paging.endIndex)
    }

    return filteredCommits
  }, [commits, filter, paging])

  const isHeadCommitVisible = useMemo<boolean>(() => {
    return visibleCommits.find(commit => commit.hash === headCommit?.hash) !== undefined
  }, [headCommit, visibleCommits])

  const { columnData, virtualColumns } = useColumnData({
    visibleCommits: visibleCommits.length
  })

  const contextValue = useMemo<GraphContextBag>(() => ({
    node: node as CustomCommitNode<unknown>,
    showCommitNodeTooltips,
    showCommitNodeHashes,
    nodeTheme,
    breakPointTheme,
    nodeSize,
    graphWidth: graphWidth + virtualColumns,
    orientation,
    visibleCommits,
    columnData,
    isHeadCommitVisible,
    highlightedBackgroundHeight,
    tooltip
  }), [node, showCommitNodeTooltips, breakPointTheme, isHeadCommitVisible, showCommitNodeHashes, nodeTheme, nodeSize, graphWidth, virtualColumns, orientation, visibleCommits, columnData, highlightedBackgroundHeight, tooltip])

  return (
    <GraphContext.Provider value={contextValue}>
      <div className={styles.container} style={{ width }} ref={ref}>
        {children}

        {enableResize && (
          <button
            onMouseDown={startResizing}
            className={styles.dragHandle}
          />
        )}
      </div>
    </GraphContext.Provider>
  )
}

// frontend/src/components/GitLog/graph/GraphCore.vue
<script setup lang="ts">
import { computed, provide, useSlots, watchEffect } from 'vue'
import { useGitContext } from '../composables/useGitContext'
import { useColumnData } from '../composables/useColumnData'
import {
  GRAPH_CONTEXT_KEY,
  type GraphContextBag,
} from '../composables/keys'
import { pxToRem } from '../utils/units'
import type {
  BreakPointTheme,
  CustomCommitNodeProps,
  CustomTooltipProps,
  GraphOrientation,
  NodeTheme,
} from '../types'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = withDefaults(defineProps<{
  nodeTheme?: NodeTheme
  breakPointTheme?: BreakPointTheme
  orientation?: GraphOrientation
  showCommitNodeHashes?: boolean
  showCommitNodeTooltips?: boolean
  highlightedBackgroundHeight?: number
}>(), {
  nodeTheme: 'default',
  breakPointTheme: 'dot',
  orientation: 'normal',
  showCommitNodeHashes: false,
  showCommitNodeTooltips: false,
})

// ---------------------------------------------------------------------------
// Slots — bridge scoped slots to render function refs for GraphContextBag
// ---------------------------------------------------------------------------

defineSlots<{
  default(): unknown
  node?(props: CustomCommitNodeProps): unknown
  tooltip?(props: CustomTooltipProps): unknown
}>()

const slots = useSlots()

const nodeSlotFn = computed(() =>
  slots.node ? (slotProps: CustomCommitNodeProps) => slots.node!(slotProps) : undefined,
)

const tooltipSlotFn = computed(() =>
  slots.tooltip ? (slotProps: CustomTooltipProps) => slots.tooltip!(slotProps) : undefined,
)

// ---------------------------------------------------------------------------
// Git context
// ---------------------------------------------------------------------------

const {
  paging,
  filter,
  headCommit,
  graphData,
  graphWidth: gitContextGraphWidth,
  nodeSize,
  setGraphOrientation,
} = useGitContext()

// Sync orientation prop to the shared GitContext so sibling components
// (e.g. Tags) can read it without accessing the GraphContext.
watchEffect(() => {
  setGraphOrientation(props.orientation)
})

// ---------------------------------------------------------------------------
// Visible commits
// ---------------------------------------------------------------------------

const visibleCommits = computed(() => {
  const commits = graphData.value.commits
  const filteredCommits = filter.value?.(commits) ?? commits

  const pagingValue = paging.value
  if (pagingValue) {
    return filteredCommits.slice(pagingValue.startIndex, pagingValue.endIndex)
  }

  return filteredCommits
})

const isHeadCommitVisible = computed<boolean>(() => {
  const head = headCommit.value
  if (!head) return false
  return visibleCommits.value.some(commit => commit.hash === head.hash)
})

// ---------------------------------------------------------------------------
// Column data
// ---------------------------------------------------------------------------

const visibleCommitsCount = computed(() => visibleCommits.value.length)

const { columnData, virtualColumns } = useColumnData(visibleCommitsCount)

// ---------------------------------------------------------------------------
// Graph context — provide to all descendants
// ---------------------------------------------------------------------------

const graphWidthWithVirtual = computed(() => graphData.value.graphWidth + virtualColumns.value)

const graphContextValue: GraphContextBag = {
  showCommitNodeHashes: computed(() => props.showCommitNodeHashes),
  showCommitNodeTooltips: computed(() => props.showCommitNodeTooltips),
  node: nodeSlotFn,
  highlightedBackgroundHeight: computed(() => props.highlightedBackgroundHeight),
  nodeTheme: computed(() => props.nodeTheme),
  breakPointTheme: computed(() => props.breakPointTheme),
  nodeSize,
  graphWidth: graphWidthWithVirtual,
  orientation: computed(() => props.orientation),
  visibleCommits,
  isHeadCommitVisible,
  columnData,
  tooltip: tooltipSlotFn,
}

provide(GRAPH_CONTEXT_KEY, graphContextValue)
</script>

<template>
  <div
    class="container"
    :style="{ width: pxToRem(gitContextGraphWidth) }"
  >
    <slot />
  </div>
</template>

<style scoped lang="scss">
.container {
  position: relative;
}

.graph {
  height: 100%;
  display: grid;
  gap: 0;
}

</style>
