// frontend/src/components/GitLog/tags/components/BranchTagTooltip.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'
import { useTheme } from '../../composables/useTheme'
import type { Commit } from '../../types'
import styles from './BranchTagTooltip.module.scss'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  id: string
  commit: Commit
}>()

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const { textColour, getTooltipBackground, getCommitColour } = useTheme()

// ---------------------------------------------------------------------------
// Computed values
// ---------------------------------------------------------------------------

const tooltipStyle = computed<CSSProperties>(() => ({
  color: textColour.value,
  background: getTooltipBackground(props.commit),
  border: `2px solid ${getCommitColour(props.commit)}`,
}))
</script>

<template>
  <div
    :id="`tag-${id}-tooltip`"
    :class="styles.tooltip"
    :style="tooltipStyle"
  >
    {{ commit.branch }}
  </div>
</template>

// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Tags/components/BranchTagTooltip/BranchTagTooltip.tsx
import styles from './BranchTagTooltip.module.scss'
import { useTheme } from 'hooks/useTheme'
import { BranchTagTooltipProps } from './types'

export const BranchTagTooltip = ({ id, commit }: BranchTagTooltipProps) => {
  const { textColour, getTooltipBackground, getCommitColour } = useTheme()

  const colour = getTooltipBackground(commit)

  return (
    <div
      className={styles.tooltip}
      id={`tag-${id}-tooltip`}
      data-testid={`tag-${id}-tooltip`}
      style={{
        color: textColour,
        background: colour,
        border: `2px solid ${getCommitColour(commit)}`,
      }}
    >
      {commit.branch}
    </div>
  )
}
