// frontend/src/components/GitLog/graph/components/CommitNodeTooltip.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'
import { useTheme } from '../../composables/useTheme'
import type { Commit } from '../../types'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  commit: Commit
  colour?: string
}>()

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const { textColour, getTooltipBackground } = useTheme()

// ---------------------------------------------------------------------------
// Computed values
// ---------------------------------------------------------------------------

const tooltipStyle = computed<CSSProperties>(() => ({
  color: textColour.value,
  border: `2px solid ${props.colour}`,
  background: getTooltipBackground(props.commit),
}))

const parentsText = computed(() =>
  props.commit.parents.length > 0 ? props.commit.parents.join(', ') : 'None',
)

const childrenText = computed(() =>
  props.commit.children.length > 0 ? props.commit.children.join(', ') : 'None',
)
</script>

<template>
  <div
    :id="`commit-node-tooltip-${commit.hash}`"
    :data-testid="`commit-node-tooltip-${commit.hash}`"
    :style="tooltipStyle"
    class="tooltip"
  >
    <div>
      <p class="label">Hash:</p>
      <p class="text">{{ commit.hash }}</p>
    </div>

    <div>
      <p class="label">Parents:</p>
      <p class="text">{{ parentsText }}</p>
    </div>

    <div>
      <p class="label">Children:</p>
      <p class="text">{{ childrenText }}</p>
    </div>

    <div>
      <p class="label">Branch Tip:</p>
      <p class="text">{{ commit.isBranchTip ? 'Yes' : 'No' }}</p>
    </div>
  </div>
</template>

<style scoped lang="scss">
.tooltip {
  padding: 15px 20px;
  border-radius: 8px;
}

.label {
  font-weight: 600;
  display: inline-block;
  margin: 0 5px 5px 0;
}

.text {
  display: inline;
  margin: 0 0 5px 0;
}
</style>

// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Graph/strategies/Grid/components/CommitNodeTooltip/CommitNodeTooltip.tsx
import { useTheme } from 'hooks/useTheme'
import styles from './CommitNodeTooltip.module.scss'
import { CommitNodeTooltipProps } from './types'

export const CommitNodeTooltip = ({ commit, color }: CommitNodeTooltipProps) => {
  const { textColour, getTooltipBackground } = useTheme()

  return (
    <div
      className={styles.tooltip}
      id={`commit-node-tooltip-${commit.hash}`}
      data-testid={`commit-node-tooltip-${commit.hash}`}
      style={{
        color: textColour,
        border: `2px solid ${color}`,
        background: getTooltipBackground(commit)
      }}
    >
      <div>
        <p className={styles.label}>
          Hash:
        </p>

        <p className={styles.text}>
          {commit.hash}
        </p>
      </div>

      <div>
        <p className={styles.label}>
          Parents:
        </p>

        <p className={styles.text}>
          {commit.parents.length > 0 ? commit.parents.join(', ') : 'None'}
        </p>
      </div>

      <div>
        <p className={styles.label}>
          Children:
        </p>

        <p className={styles.text}>
          {commit.children.length > 0 ? commit.children.join(', ') : 'None'}
        </p>
      </div>

      <div>
        <p className={styles.label}>
          Branch Tip:
        </p>

        <p className={styles.text}>
          {commit.isBranchTip ? 'Yes' : 'No'}
        </p>
      </div>
    </div>
  )
}
