// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Tags/components/Link/Link.tsx
import classNames from 'classnames'
import styles from './Link.module.scss'
import { useTheme } from 'hooks/useTheme'
import { LinkProps } from './types'

export const Link = ({ href, text, className, ...props }: LinkProps) => {
  const { textColour } = useTheme()
  
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      style={{ color: textColour }}
      className={classNames(styles.link, className)}
      {...props}
    >
      {text}
    </a>
  )
}

// frontend/src/components/GitLog/tags/components/Link.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'
import { useTheme } from '../../composables/useTheme'
import styles from './Link.module.scss'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

defineProps<{
  href?: string
  text: string
  linkClass?: string
}>()

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const { textColour } = useTheme()

// ---------------------------------------------------------------------------
// Computed values
// ---------------------------------------------------------------------------

const linkStyle = computed<CSSProperties>(() => ({
  color: textColour.value,
}))
</script>

<template>
  <a
    :href="href"
    target="_blank"
    rel="noopener noreferrer"
    :style="linkStyle"
    :class="[styles.link, linkClass]"
  >
    {{ text }}
  </a>
</template>
