// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Tags/components/TagLabel/TagLabel.tsx
import { useGitContext } from 'context/GitContext'
import { formatBranch } from 'modules/Tags/utils/formatBranch'
import { useMemo } from 'react'
import styles from './TagLabel.module.scss'
import { Link } from '../Link'
import { TagIcon } from '../TagIcon'
import { TagLabelProps } from './types'

export const TagLabel = ({ commit }: TagLabelProps) => {
  const { remoteProviderUrlBuilder } = useGitContext()

  const displayName = formatBranch(commit.branch)

  const linkHref = useMemo(() => {
    if (remoteProviderUrlBuilder) {
      return remoteProviderUrlBuilder({ commit }).branch
    }
  }, [commit, remoteProviderUrlBuilder])

  if (linkHref) {
    return (
      <>
        <Link
          href={linkHref}
          text={displayName}
          className={styles.tagName}
        />

        <TagIcon />
      </>
    )
  }

  return (
    <>
      <span className={styles.tagName}>
        {displayName}
      </span>

      <TagIcon  />
    </>
  )
}

// frontend/src/components/GitLog/tags/components/TagLabel.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useGitContext } from '../../composables/useGitContext'
import { formatBranch } from '../../utils/formatBranch'
import type { Commit } from '../../types'
import Link from './Link.vue'
import TagIcon from './TagIcon.vue'
import styles from './TagLabel.module.scss'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  commit: Commit
}>()

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const { remoteProviderUrlBuilder } = useGitContext()

// ---------------------------------------------------------------------------
// Computed values
// ---------------------------------------------------------------------------

const displayName = computed(() => formatBranch(props.commit.branch))

const linkHref = computed(() => {
  if (remoteProviderUrlBuilder.value) {
    return remoteProviderUrlBuilder.value({ commit: props.commit }).branch
  }
  return undefined
})
</script>

<template>
  <template v-if="linkHref">
    <Link
      :href="linkHref"
      :text="displayName"
      :link-class="styles.tagName"
    />
    <TagIcon />
  </template>

  <template v-else>
    <span :class="styles.tagName">
      {{ displayName }}
    </span>
    <TagIcon />
  </template>
</template>
