// frontend/src/components/GitLog/table/components/AuthorData.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'
import type { CommitAuthor } from '../../types'
import styles from './AuthorData.module.scss'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  index: number
  author?: CommitAuthor
  isPlaceholder: boolean
  style?: CSSProperties
}>()

// ---------------------------------------------------------------------------
// Computed
// ---------------------------------------------------------------------------

const authorTitle = computed(() => {
  if (props.author) {
    if (props.author.name && props.author.email) {
      return `${props.author.name} (${props.author.email})`
    }

    if (props.author.name && !props.author.email) {
      return props.author.name
    }

    if (props.author.email && !props.author.name) {
      return props.author.email
    }
  }

  return undefined
})

const authorName = computed(() => {
  if (props.author?.name) {
    return props.author.name
  }

  return ''
})
</script>

<template>
  <div
    :style="style"
    :title="authorTitle"
    :class="styles.author"
    :id="`vue-git-log-table-data-author-${index}`"
    :data-testid="`vue-git-log-table-data-author-${index}`"
  >
    {{ isPlaceholder ? '-' : authorName }}
  </div>
</template>

// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Table/components/AuthorData/AuthorData.tsx
import styles from './AuthorData.module.scss'
import { AuthorDataProps } from './types'
import { useMemo } from 'react'

export const AuthorData = ({ author, index, style, isPlaceholder }: AuthorDataProps) => {
  const authorTitle = useMemo(() => {
    if (author) {
      if (author.name && author.email) {
        return `${author.name} (${author.email})`
      }

      if (author.name && !author.email) {
        return author.name
      }

      if (author.email && !author.name) {
        return author.email
      }
    }

    return undefined
  }, [author])

  const authorName = useMemo(() => {
    if (author?.name) {
      return author.name
    }

    return ''
  }, [author])
  
  return (
    <div
      style={style}
      title={authorTitle}
      className={styles.author}
      id={`react-git-log-table-data-author-${index}`}
      data-testid={`react-git-log-table-data-author-${index}`}
    >
      {isPlaceholder ? '-' : authorName}
    </div>
  )
}
