// frontend/src/components/GitLog/table/components/CommitMessageData.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue'
import IndexStatus from './IndexStatus.vue'
import styles from './CommitMessageData.module.scss'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

defineProps<{
  index: number
  isIndex: boolean
  commitMessage: string
  style?: CSSProperties
}>()
</script>

<template>
  <div
    :title="commitMessage"
    :class="styles.message"
    :id="`vue-git-log-table-data-commit-message-${index}`"
    :style="{ ...style, display: isIndex ? 'flex' : undefined }"
    :data-testid="`vue-git-log-table-data-commit-message-${index}`"
  >
    {{ commitMessage }}

    <IndexStatus v-if="isIndex" />
  </div>
</template>

// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Table/components/CommitMessageData/CommitMessageData.tsx
import styles from './CommitMessageData.module.scss'
import { CommitMessageDataProps } from './types'
import { IndexStatus } from 'modules/Table/components/IndexStatus'

export const CommitMessageData = ({ index, isIndex, commitMessage, style }: CommitMessageDataProps) => {
  return (
    <div
      title={commitMessage}
      className={styles.message}
      id={`react-git-log-table-data-commit-message-${index}`}
      style={{ ...style, display: isIndex ? 'flex' : undefined }}
      data-testid={`react-git-log-table-data-commit-message-${index}`}
    >
      {commitMessage}

      {isIndex && (
        <IndexStatus />
      )}
    </div>
  )
}
