// frontend/src/components/GitLog/graph/components/ColumnBackground.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'
import { BACKGROUND_HEIGHT_OFFSET, ROW_HEIGHT } from '../../constants'
import { useGitContext } from '../../composables/useGitContext'
import { useGraphContext } from '../../composables/useGraphContext'
import { getColumnBackgroundSize } from '../utils/getColumnBackgroundSize'
import styles from './ColumnBackground.module.scss'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  id: string
  index: number
  colour: string
  commitNodeIndex: number
}>()

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const { showTable } = useGitContext()
const { nodeSize, orientation, highlightedBackgroundHeight } = useGraphContext()

// ---------------------------------------------------------------------------
// Computed values
// ---------------------------------------------------------------------------

const height = computed<number>(() => {
  if (highlightedBackgroundHeight.value) {
    return highlightedBackgroundHeight.value
  }

  const dynamicHeight = nodeSize.value + BACKGROUND_HEIGHT_OFFSET
  return dynamicHeight > ROW_HEIGHT ? ROW_HEIGHT : dynamicHeight
})

const backgroundStyle = computed<CSSProperties>(() => {
  const offset = getColumnBackgroundSize({ nodeSize: nodeSize.value })

  if (!showTable.value) {
    const backgroundSize = nodeSize.value + offset

    return {
      borderRadius: '50%',
      height: `${backgroundSize}px`,
      width: `${backgroundSize}px`,
      background: props.colour,
      left: `calc(50% - ${backgroundSize / 2}px)`,
    }
  }

  if (props.index === props.commitNodeIndex) {
    return {
      width: `calc(50% + ${nodeSize.value / 2}px + ${offset / 2}px)`,
      height: `${height.value}px`,
      background: props.colour,
      right: '0',
      borderTopLeftRadius: '50%',
      borderBottomLeftRadius: '50%',
    }
  }

  return {
    height: `${height.value}px`,
    background: props.colour,
  }
})

const shouldShowFullBackground = computed(() =>
  orientation.value === 'normal'
    ? props.index > props.commitNodeIndex
    : props.index < props.commitNodeIndex,
)
</script>

<template>
  <div
    :id="`column-background-${index}-${id}`"
    :data-testid="`column-background-${index}-${id}`"
    :style="backgroundStyle"
    :class="[
      styles.background,
      shouldShowFullBackground && styles.backgroundSquare,
    ]"
  />
</template>

// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Graph/strategies/Grid/components/ColumnBackground/ColumnBackground.tsx
import { ColumnBackgroundProps } from './types'
import classNames from 'classnames'
import styles from './ColumnBackground.module.scss'
import { CSSProperties, useMemo } from 'react'
import { BACKGROUND_HEIGHT_OFFSET, ROW_HEIGHT } from 'constants/constants'
import { useGitContext } from 'context/GitContext'
import { useGraphContext } from 'modules/Graph/context'
import { getColumnBackgroundSize } from 'modules/Graph/utils/getColumnBackgroundSize'

export const ColumnBackground = ({ id, index, colour, commitNodeIndex }: ColumnBackgroundProps) => {
  const { showTable } = useGitContext()
  const { nodeSize, orientation, highlightedBackgroundHeight } = useGraphContext()

  const height = useMemo<number>(() => {
    if (highlightedBackgroundHeight) {
      return highlightedBackgroundHeight
    }

    const dynamicHeight = nodeSize + BACKGROUND_HEIGHT_OFFSET
    return dynamicHeight > ROW_HEIGHT ? ROW_HEIGHT : dynamicHeight
  }, [highlightedBackgroundHeight, nodeSize])

  const style = useMemo<CSSProperties>(() => {
    const offset = getColumnBackgroundSize({ nodeSize })

    if (!showTable) {
      const backgroundSize = nodeSize + offset

      return {
        borderRadius: '50%',
        height: `${backgroundSize}px`,
        width: `${backgroundSize}px`,
        background: colour,
        left: `calc(50% - ${backgroundSize / 2}px)`
      }
    }


    if (index === commitNodeIndex) {
      return {
        width: `calc(50% + ${nodeSize / 2}px + ${offset / 2}px)`,
        height,
        background: colour,
        right: 0,
        borderTopLeftRadius: '50%',
        borderBottomLeftRadius: '50%'
      }
    }

    return {
      height,
      background: colour
    }
  }, [nodeSize, showTable, index, commitNodeIndex, height, colour])

  const shouldShowFullBackground = orientation === 'normal'
    ? index > commitNodeIndex
    : index < commitNodeIndex
  
  return (
    <div
      id={`column-background-${index}-${id}`}
      data-testid={`column-background-${index}-${id}`}
      style={style}
      className={classNames(
        styles.background,
        { [styles.backgroundSquare]: shouldShowFullBackground }
      )}
    />
  )
}
