// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Table/components/IndexStatus/IndexStatus.tsx
import styles from './IndexStatus.module.scss'
import Pencil from 'assets/pencil.svg?react'
import Plus from 'assets/plus.svg?react'
import Minus from 'assets/minus.svg?react'
import { useGitContext } from 'context/GitContext'
import classNames from 'classnames'

export const IndexStatus = () => {
  const { indexStatus } = useGitContext()

  if (!indexStatus) {
    return null
  }

  return (
    <div className={styles.indexStatus} data-testid='index-status'>
      {indexStatus.modified > 0 && (
        <div data-testid='index-status-modified' className={styles.status}>
          <span className={classNames(styles.value, styles.modified)}>
            {indexStatus.modified}
          </span>

          <div className={styles.iconWrapper}>
            <Pencil className={styles.pencil} />
          </div>
        </div>
      )}

      {indexStatus.added > 0 && (
        <div data-testid='index-status-added' className={styles.status}>
          <span className={classNames(styles.value, styles.added)}>
            {indexStatus.added}
          </span>

          <div className={styles.iconWrapper}>
            <Plus className={styles.plus} />
          </div>
        </div>
      )}

      {indexStatus.deleted > 0 && (
        <div data-testid='index-status-deleted' className={styles.status}>
          <span className={classNames(styles.value, styles.deleted)}>
            {indexStatus.deleted}
          </span>

          <div className={styles.iconWrapper}>
            <Minus className={styles.minus} />
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/src/components/GitLog/table/components/IndexStatus.vue
<script setup lang="ts">
import { useGitContext } from '../../composables/useGitContext'
import pencilIcon from '../../assets/pencil.svg'
import plusIcon from '../../assets/plus.svg'
import minusIcon from '../../assets/minus.svg'
import styles from './IndexStatus.module.scss'

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const { indexStatus } = useGitContext()
</script>

<template>
  <div
    v-if="indexStatus"
    :class="styles.indexStatus"
    data-testid="index-status"
  >
    <div
      v-if="indexStatus.modified > 0"
      :class="styles.status"
      data-testid="index-status-modified"
    >
      <span :class="[styles.value, styles.modified]">
        {{ indexStatus.modified }}
      </span>

      <div :class="styles.iconWrapper">
        <img :src="pencilIcon" :class="styles.pencil" alt="modified">
      </div>
    </div>

    <div
      v-if="indexStatus.added > 0"
      :class="styles.status"
      data-testid="index-status-added"
    >
      <span :class="[styles.value, styles.added]">
        {{ indexStatus.added }}
      </span>

      <div :class="styles.iconWrapper">
        <img :src="plusIcon" :class="styles.plus" alt="added">
      </div>
    </div>

    <div
      v-if="indexStatus.deleted > 0"
      :class="styles.status"
      data-testid="index-status-deleted"
    >
      <span :class="[styles.value, styles.deleted]">
        {{ indexStatus.deleted }}
      </span>

      <div :class="styles.iconWrapper">
        <img :src="minusIcon" :class="styles.minus" alt="deleted">
      </div>
    </div>
  </div>
</template>
