// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Table/components/TimestampData/TimestampData.tsx
import styles from './TimestampData.module.scss'
import { TimestampDataProps } from './types'
import { useMemo } from 'react'
import dayjs from 'dayjs'
import utc from 'dayjs/plugin/utc'
import relativeTime from 'dayjs/plugin/relativeTime'
import { useTableContext } from 'modules/Table/context'

dayjs.extend(utc)
dayjs.extend(relativeTime)

export const TimestampData = ({ index, timestamp, isPlaceholder, style }: TimestampDataProps) => {
  const { timestampFormat } = useTableContext()

  const formattedTimestamp = useMemo(() => {
    const commitDate = dayjs.utc(timestamp)

    if (dayjs.utc().diff(commitDate, 'week') >= 1) {
      return commitDate.format(timestampFormat)
    }

    return commitDate.fromNow()
  }, [timestamp, timestampFormat])

  return (
    <div
      style={style}
      className={styles.timestamp}
      id={`react-git-log-table-data-timestamp-${index}`}
      data-testid={`react-git-log-table-data-timestamp-${index}`}
    >
      {isPlaceholder ? '-' : formattedTimestamp}
    </div>
  )
}

// frontend/src/components/GitLog/table/components/TimestampData.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'
import dayjs from 'dayjs'
import utc from 'dayjs/plugin/utc'
import relativeTime from 'dayjs/plugin/relativeTime'
import { useTableContext } from '../../composables/useTableContext'
import styles from './TimestampData.module.scss'

// ---------------------------------------------------------------------------
// dayjs plugins
// ---------------------------------------------------------------------------

dayjs.extend(utc)
dayjs.extend(relativeTime)

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  index: number
  timestamp: string
  isPlaceholder: boolean
  style?: CSSProperties
}>()

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const { timestampFormat } = useTableContext()

// ---------------------------------------------------------------------------
// Computed
// ---------------------------------------------------------------------------

const formattedTimestamp = computed(() => {
  const commitDate = dayjs.utc(props.timestamp)

  if (dayjs.utc().diff(commitDate, 'week') >= 1) {
    return commitDate.format(timestampFormat.value)
  }

  return commitDate.fromNow()
})
</script>

<template>
  <div
    :style="style"
    :class="styles.timestamp"
    :id="`vue-git-log-table-data-timestamp-${index}`"
    :data-testid="`vue-git-log-table-data-timestamp-${index}`"
  >
    {{ isPlaceholder ? '-' : formattedTimestamp }}
  </div>
</template>
