// frontend/src/components/GitLog/tags/components/BranchLabel.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useGitContext } from '../../composables/useGitContext'
import { formatBranch } from '../../utils/formatBranch'
import type { Commit } from '../../types'
import Link from './Link.vue'
import BranchIcon from './BranchIcon.vue'
import styles from './BranchLabel.module.scss'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  commit: Commit
}>()

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const { remoteProviderUrlBuilder } = useGitContext()

// ---------------------------------------------------------------------------
// Computed values
// ---------------------------------------------------------------------------

const displayName = computed(() => formatBranch(props.commit.branch))

const linkHref = computed(() => {
  return remoteProviderUrlBuilder.value?.({ commit: props.commit })?.branch
})
</script>

<template>
  <template v-if="linkHref">
    <Link
      :href="linkHref"
      :text="displayName"
      :link-class="styles.branchName"
    />
    <BranchIcon />
  </template>

  <template v-else>
    <span :class="styles.branchName">
      {{ displayName }}
    </span>
    <BranchIcon />
  </template>
</template>

// docs/specs/2026-02-09-git-log/react-git-log-source/modules/Tags/components/BranchLabel/BranchLabel.tsx
import { useGitContext } from 'context/GitContext'
import styles from './BranchLabel.module.scss'
import { formatBranch } from 'modules/Tags/utils/formatBranch'
import { useMemo } from 'react'
import { Link } from '../Link'
import { BranchIcon } from '../BranchIcon'
import { BranchLabelProps } from './types'

export const BranchLabel = ({ commit }: BranchLabelProps) => {
  const { remoteProviderUrlBuilder } = useGitContext()

  const displayName = formatBranch(commit.branch)

  const linkHref = useMemo(() => {
    const branchLink = remoteProviderUrlBuilder?.({ commit }).branch

    if (branchLink) {
      return branchLink
    }
  }, [commit, remoteProviderUrlBuilder])

  if (linkHref) {
    return (
      <>
        <Link
          href={linkHref}
          text={displayName}
          className={styles.branchName}
        />

        <BranchIcon
          className={styles.icon}
        />
      </>
    )
  }

  return (
    <>
      <span className={styles.branchName}>
        {displayName}
      </span>

      <BranchIcon
        className={styles.icon}
      />
    </>
  )
}
